### ISSUE TITLE
module initialization error 's3://mybucket/demo-params.json

### ISSUE THREAD

**Issue by miansn** [YannMjl/AWS-lambda-functions#1]
I am using AWS-lambda-function to launch my CF template, but it ends in error like this

module initialization error
's3://my bucket/demo-params.json

my files are attached please
[RDS_oracletemplate.txt](https://github.com/YannMjl/AWS-lambda-functions/files/5842606/RDS_oracletemplate.txt)
[Lambda function.txt](https://github.com/YannMjl/AWS-lambda-functions/files/5842615/Lambda.function.txt)

and using following parameters

[
    {
        "ParameterKey": "Engine",
        "ParameterValue": "oracle-ee"
    }
]

please guide or correct my code. thanks

**Comment by YannMjl** [comment]
This error is comming from your lambda function:

params_url = os.environ['s3://mybucket/demo-params.json']
template_url = os.environ['https://mybucket.s3.amazonaws.com/RDS_Oracletemplate.json']

You shouldn't pass those params from the script.

The Lambda function is set up with two variables, templateUrl and paramsFile, that point to your input template URL and parameters file. 
If in the future you want to test with a different template and input parameters, you can use the Lambda console to update the environment variables of the Lambda function.
The Lambda function has been granted the Administrator role to allow AWS CloudFormation to create any AWS resources that are defined in your template.

Those lines of code should like something like this:

params_url = os.environ['paramsFile']
template_url = os.environ['templateUrl']

Your script should like something like this:
https://gist.github.com/YannMjl/043971809498c4724beaead44bdc3dad
